#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 100:00:00
#SBATCH -J Phylophlan
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools phylophlan/0.99
module unload python
module load python/2.7.15 biopython/1.73 FastTree muscle/3.8.31 usearch/5.2.32

# Sequence directories
INDIR="/crex/proj/genomeanalysis2022/nobackup/work/andreak/Prokka"
OUTDIR="/crex/proj/genomeanalysis2022/nobackup/work/andreak/Phylophlan_New"

# Copy installed phylophlan files into working directory. 
cp -r /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/* $OUTDIR/

# Symlink the phylophlan data files
cd  $OUTDIR/
mkdir data
cd data
mkdir -p ppaalns
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/*.bz2 .
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppaalns/*.bz2 ppaalns/
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppafull.tax.txt .
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/taxcuration/ $OUTDIR/taxcuration

# Soft link the input data to phylophlans input directory
ln -s $INDIR/D1/*ann.out/*.faa $OUTDIR/input/D1/
ln -s $INDIR/D3/*ann.out/*.faa $OUTDIR/input/D3/

# Run pylophlan 
cd $OUTDIR
phylophlan.py -i D1 -t --nproc 2 2> D1_phylo.err
phylophlan.py -i D3 -t --nproc 2 2> D3_phylo.err
