#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 02:00:00
#SBATCH -J test_checkm
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools
module load CheckM

# Set directories
INDIR="/home/andreak/Genome_Analysis/Genome-Analysis/data/Metabat"
OUTDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Test_ChechM"


# Set a working directory that we want
cd $OUTDIR 

# Copy the CheckM data
cp -av $CHECKM_DATA/2015_01_16/* .
checkm data setRoot $PWD


module load bioinfo-tools
module load CheckM

# CheckM commands to run

checkm len_plot -x fa $INDIR/D1_metabat $OUTDIR/D1/D1_len_plots
checkm len_plot -x fa $INDIR/D3_metabat $OUTDIR/D3/D3_len_plots


checkm len_hist -x fa $INDIR/D1_metabat $OUTDIR/D1/D1_len_hist
checkm len_hist -x fa $INDIR/D3_metabat $OUTDIR/D3/D3_len_hist

checkm unbinned -x fa $INDIR/D1_metabat /home/andreak/Genome_Analysis/Genome-Analysis/data/Megahit/D1-SRR4342129_contigs/final.contigs.fa D1_unbinned.out D1_unbinned_stats.out
checkm unbinned -x fa $INDIR/D3_metabat /home/andreak/Genome_Analysis/Genome-Analysis/data/Megahit/D3-SRR4342133_contigs/final.contigs.fa D3_unbinned.out D3_unbinned_stats.out

checkm tetra -t 2 /home/andreak/Genome_Analysis/Genome-Analysis/data/Megahit/D1-SRR4342129_contigs/final.contigs.fa $OUTDIR/D1/D1_tetra.out
checkm tetra -t 2 /home/andreak/Genome_Analysis/Genome-Analysis/data/Megahit/D3-SRR4342133_contigs/final.contigs.fa $OUTDIR/D3/D3_tetra.out

# Taxonomy pipeline which includes taxon_set, analyze and qa.

checkm taxonomy_wf -t 2 -x fa domain Bacteria $INDIR/D1_metabat $OUTDIR/D1/D1_taxonomy_wf
checkm taxonomy_wf -t 2 -x fa domain Bacteria $INDIR/D3_metabat $OUTDIR/D3/D3_taxonomy_wf

# Extra QA because I wanted better output

checkm qa -t 2 -o 2 $OUTDIR/D1/D1_taxonomy_wf/Bacteria.ms $OUTDIR/D1/D1_taxonomy_wf > $OUTDIR/D1/D1_qa.out
checkm qa -t 2 -o 2 $OUTDIR/D3/D3_taxonomy_wf/Bacteria.ms $OUTDIR/D3/D3_taxonomy_wf > $OUTDIR/D3/D3_qa.out

# Finally, running the qa plot

checkm bin_qa_plot -x fa $OUTDIR/D1/D1_taxonomy_wf $INDIR/D1_metabat $OUTDIR/D1/D1_bin_qa_plot
checkm bin_qa_plot -x fa $OUTDIR/D3/D3_taxonomy_wf $INDIR/D3_metabat $OUTDIR/D3/D3_bin_qa_plot
