#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 02:00:00
#SBATCH -J test_checkm
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools
module load CheckM

# Set directories
INDIR="/home/andreak/Genome_Analysis/Genome-Analysis/data/Metabat"
OUTDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Test_ChechM"


# Set a working directory that we want
cd $OUTDIR 

# Copy the CheckM data
cp -av $CHECKM_DATA/2015_01_16/* .
checkm data setRoot $PWD


module load bioinfo-tools
module load CheckM

# CheckM commands to run
checkm tree -x fa --reduced_tree $INDIR/D1_metabat $OUTDIR/D1/
checkm tree -x fa --reduced_tree $INDIR/D1_metabat $OUTDIR/D3/

checkm tree_qa $OUTDIR/D1/ -o 2 > $OUTDIR/D1/
checkm tree_qa $OUTDIR/D3/ -o 2 > $OUTDIR/D3/

checkm lineage_set $OUTDIR/D1/ $OUTDIR/D1/D1_marker
checkm lineage_set $OUTDIR/D3/ $OUTDIR/D3/D3_marker

checkm lineage_wf -t 4 -x fa --reduced_tree $INDIR/D1_metabat $OUTDIR/D1/D1_lineage_wf
checkm lineage_wf -t 4 -x fa --reduced_tree $INDIR/D1_metabat $OUTDIR/D3/D3_lineage_wf

mkdir $OUTDIR/D1/D1_analyze
mkdir $OUTDIR/D3/D3_analyze
checkm analyze -x fa $OUTDIR/D1/D1_marker $INDIR/D1_metabat $OUTDIR/D1/D1_analyze
checkm analyze -x fa $OUTDIR/D3/D3_marker $INDIR/D3_metabat $OUTDIR/D3/D3_analyze


# Taxonomy pipeline which includes taxon_set, analyze and qa.
#checkm taxonomy_wf -t 2 -x fa domain Bacteria $INDIR/D1_metabat $OUTDIR/D1/D1_taxonomy_wf
#checkm taxonomy_wf -t 2 -x fa domain Bacteria $INDIR/D3_metabat $OUTDIR/D3/D3_taxonomy_wf

# Extra QA because I wanted better output

checkm qa -t 2 -o 2 $OUTDIR/D1/D1_marker $OUTDIR/D1/D1_analyze > $OUTDIR/D1/D1_qa.out
checkm qa -t 2 -o 2 $OUTDIR/D3/D3_marker $OUTDIR/D3/D3_analyze > $OUTDIR/D3/D3_qa.out

# Finally, running the qa plot
#checkm bin_qa_plot -x fa $OUTDIR/D1/D1_taxonomy_wf $INDIR/D1_metabat $OUTDIR/D1/D1_bin_qa_plot
#checkm bin_qa_plot -x fa $OUTDIR/D3/D3_taxonomy_wf $INDIR/D3_metabat $OUTDIR/D3/D3_bin_qa_plot
