#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 03:00:00
#SBATCH -J prokka
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools
module load prokka

# Sequence directories
#SEQDIR="/home/andreak/Genome_Analysis/Genome-Analysis/data/Metabat_depth/"
#OUTDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Prokka"

# Loop for annotation of all .fa 
for fa in /home/andreak/Genome_Analysis/Genome-Analysis/data/Metabat_depth/D1_metabat_depth/*
do
echo $fa
prokka --metagenome --cpus 2 $fa --outdir /proj/genomeanalysis2022/nobackup/work/andreak/Prokka/D1/"$fa"_ann.out
done

for fb in /home/andreak/Genome_Analysis/Genome-Analysis/data/Metabat_depth//D3_metabat_depth/*
do
echo $fb
prokka --metagenome --cpus 2 $fb --outdir /proj/genomeanalysis2022/nobackup/work/andreak/Prokka/D3/"$fb"_ann.out
done
