#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 100:00:00
#SBATCH -J eggnogmapper
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools
module load eggNOG-mapper

# Create files
cd /proj/genomeanalysis2022/nobackup/work/andreak
mkdir Eggnogmapper
cd Eggnogmapper
mkdir D1
mkdir D3

# Sequence directories
INDIR="/home/andreak/Genome_Analysis/Genome-Analysis/data/Metabat_depth/"
OUTDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Prokka"

cd $INDIR/D1
# Loop
for fa in *
do
echo $fa
emapper.py --itype metagenome -i $fa -o $fa --output_dir $OUTDIR/D1
done

cd $INDIR/D3
for fa in *
do
echo $fa
emapper.py --itype metagenome -i $fa -o $fa --output_dir $OUTDIR/D3
done
