#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 10:00:00
#SBATCH -J BWA_RNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools
module load bwa
module load samtools

# Sequence directories
INDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Prokka"
SEQDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Trimmomatic"
OUTDIR="/proj/genomeanalysis2022/nobackup/work/andreak"

#sample D1
#cd /proj/genomeanalysis2022/nobackup/work/andreak/Prokka/D1/
#for bin in *.out
#do
#for file in /proj/genomeanalysis2022/nobackup/work/andreak/Prokka/D1/$bin/*.ffn
#do
#basename_file=$(basename -s .ffn $file)
#bwa index $file
#bwa mem -t 10 $file $SEQDIR/RNA_trim_37.left_paired.trimmed.fastq.gz $SEQDIR/RNA_trim_37.right_paired.trimmed.fastq.gz 2>$OUTDIR/bwa-genes/D1/${basename_file}.sam | samtools sort -o $OUTDIR/bwa-genes/D1/${basename_file}_sorted.bam
#done
#done


#sample D3
cd /proj/genomeanalysis2022/nobackup/work/andreak/Prokka/D3/
for bin in *.out
do
for file in /proj/genomeanalysis2022/nobackup/work/andreak/Prokka/D3/$bin/*.ffn
do
basename_file=$(basename -s .ffn $file)
bwa index $file
bwa mem -t 10 $file $SEQDIR/RNA_trim_39.left_paired.trimmed.fastq.gz $SEQDIR/RNA_trim_39.right_paired.trimmed.fastq.gz 2>$OUTDIR/bwa-genes/D3/${basename_file}.sam | samtools sort -o $OUTDIR/bwa-genes/D3/${basename_file}_sorted.bam
done
done

