#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 10:00:00
#SBATCH -J BWA_RNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools
module load bwa
module load samtools

# Sequence directories
INDIR="/home/andreak/Genome_Analysis/Genome-Analysis/data/Metabat_depth"
SEQDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Trimmomatic"
OUTDIR="/proj/genomeanalysis2022/nobackup/work/andreak/"

#onebyone
#sample D1
#BWA first needs to construct the FM-index for the reference genome (the index command) -- bwa index ref.fa
#cd $INDIR/D1_metabat_depth
#for bin in *.fa
#do
#bwa index $bin 
#bwa mem -t 10 $bin $SEQDIR/RNA_trim_37.left_paired.trimmed.fastq.gz $SEQDIR/RNA_trim_37.right_paired.trimmed.fastq.gz 2>$OUTDIR/bwa-rna/D1/${bin}.sam | samtools sort -o $OUTDIR/bwa-rna/D1/${bin}_sorted.bam
#done

#sample D3
cd $INDIR/D3_metabat_depth
for bin in *.fa
do
bwa index $bin 
bwa mem -t 10 $bin $SEQDIR/RNA_trim_39.left_paired.trimmed.fastq.gz $SEQDIR/RNA_trim_39.right_paired.trimmed.fastq.gz 2>$OUTDIR/bwa-rna/D3/${bin}.sam | samtools sort -o $OUTDIR/bwa-rna/D3/${bin}_sorted.bam
done

