#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 10:00:00
#SBATCH -J BWA_RNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools
module load bwa
module load samtools

# Sequence directories
INDIR="/home/andreak/Genome_Analysis/Genome-Analysis/data/Metabat_depth"
SEQDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Trimmomatic"
OUTDIR="/proj/genomeanalysis2022/nobackup/work/andreak/"


# Combine all .fa bin files into one aggregated file
# D1
cd $INDIR/D1_metabat_depth/
for n in D1-SRR4342129__metabat_depth_output.*.fa
do
cp $INDIR/D1_metabat_depth/${n} $OUTDIR/Metabat_norm/D1/${n} #πρεπει να δημιουργησω τους φακελους Metabat_norm & D1 στο nobackup
bwa index $OUTDIR/Metabat_norm/D1/${n} 2> $OUTDIR/bwa-rna/D1/${n}_index.out #πρεπει να δημιουργησω τους φακελους D1 στο nobackup μεσα στο bwa-rna

cd $OUTDIR/Metabat_norm/D1
bwa mem $OUTDIR/Metabat_norm/D1/${n} $SEQDIR/RNA_trim_39.left_paired.trimmed.fastq.gz $SEQDIR/RNA_trim_39.right_paired.trimmed.fastq.gz 2> $OUTDIR/bwa-rna/D1/${n}_mem.out | samtools sort -o $OUTDIR/bwa-rna/D1/${n}_sorted.bam
done

cd /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1/normalize
for n in D1.normalize.*.fa
do
cp /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/binning/D1/normalize/${n} /proj/genomeanalysis2022/nobackup/work/pcr/output/mapping/D1/normalize/try/${n}
bwa index /proj/genomeanalysis2022/nobackup/work/pcr/output/mapping/D1/normalize/try/${n} 2> /proj/genomeanalysis2022/nobackup/work/pcr/output/mapping/D1/normalize/try/${n}_index.out

cd /proj/genomeanalysis2022/nobackup/work/pcr/output/mapping/D1/normalize/try 
#Alignment algorithms are invoked with different sub-commands: aln/samse/sampe for BWA-backtrack, bwasw for BWA-SW and mem for the BWA-MEM algorithm -- bwa mem ref.fa read1.fq read2.fq > aln-pe.sam | Sort the alignments for later processing and store in a binary format -- samtools sort sample.sam -o sample.bam 
bwa mem /proj/genomeanalysis2022/nobackup/work/pcr/output/mapping/D1/normalize/try/${n} /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trimmed/RNA_trim_SRR4342137.forward_paired.trimmed.fastq.gz /home/pcr98/GenomeAnalysis/GenomeAnalysis/output/RNA_trimmed/RNA_trim_SRR4342137.reverse_paired.trimmed.fastq.gz 2>/proj/genomeanalysis2022/nobackup/work/pcr/output/mapping/D1/normalize/try/${n}_mem.out | samtools sort -o /proj/genomeanalysis2022/nobackup/work/pcr/output/mapping/D1/normalize/try/${n}_sorted.bam
done
