#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 10:00:00
#SBATCH -J Samtools
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Reading RNA coverage using samtools  

# Load modules 
module load bioinfo-tools 
module load samtools

# Sequence directories
INDIR="/proj/genomeanalysis2022/nobackup/work/andreak/bwa-rna"
OUTDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Samtools/"

#sample D1
cd $INDIR/D1
for i in D1.*_sorted.bam
do
samtools index ${i}
samtools view $INDIR/D1/${i} -o $OUTDIR/D1/${i}.sam
samtools coverage $INDIR/D1/${i} -o $OUTDIR/D1/${i}_coverage
samtools depth $INDIR/D1/${i} -o $OUTDIR/D1/${i}_depth
samtools stats $INDIR/D1/${i} | grep ^SN | cut -f 2- > $OUTDIR/D1/${i}_summary  
done
