#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 10:00:00
#SBATCH -J htseq
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools
module load htseq 
module load samtools 

# Sequence directories
INDIR="/proj/genomeanalysis2022/nobackup/work/andreak"
OUTDIR="/proj/genomeanalysis2022/nobackup/work/andreak/Htseq"


# Index bam files
#cd /proj/genomeanalysis2022/nobackup/work/andreak/bwa-rna/D1/
#for bam in *.bam
#do
#echo $bam
#samtools index $bam
#done 

# Run htseq
#cd /proj/genomeanalysis2022/nobackup/work/andreak/Eggnogmapper/D1/
#for gff in *.gff 
#do
#echo $gff
#bin=$(echo $gff | cut -f2 -d ".")
#echo $bin
#cd $OUTDIR/D1/
#mkdir $bin
#cd $bin
#htseq-count -f bam -t CDS -r pos -i ID $INDIR/bwa-rna/D1/D1-SRR4342129__metabat_depth_output.${bin}.fa_sorted.bam $INDIR/Eggnogmapper/D1/$gff > $OUTDIR/D1/D1_htseq_${bin}.counts
#done

# Index bam files
cd /proj/genomeanalysis2022/nobackup/work/andreak/bwa-rna/D3/
for bam in *.bam
do
echo $bam
samtools index $bam
done 

# Run htseq
cd /proj/genomeanalysis2022/nobackup/work/andreak/Eggnogmapper/D3/
for gff in *.gff 
do
echo $gff
bin=$(echo $gff | cut -f2 -d ".")
echo $bin
cd $OUTDIR/D3/
mkdir $bin
cd $bin
htseq-count -f bam -t CDS -r pos -i ID $INDIR/bwa-rna/D3/D3-SRR4342133__metabat_depth_output.${bin}.fa_sorted.bam $INDIR/Eggnogmapper/D3/$gff > $OUTDIR/D3/D3_htseq_${bin}.counts
done
