#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 15:00:00
#SBATCH -J BWA_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se

# Load modules
module load bioinfo-tools
module load bwa
module load MetaBat
module load samtools

# My commands to align my reads (raw DNA data) to my reference (megahit results)
# For D1
bwa index /home/andreak/Genome_Analysis/Genome-Analysis/data/Megahit/D1-SRR4342129_contigs/final.contigs.fa
bwa mem -t 10 /home/andreak/Genome_Analysis/Genome-Analysis/data/Megahit/D1-SRR4342129_contigs/final.contigs.fa /home/andreak/Genome_Analysis/Genome-Analysis/raw_data/3_Thrash_2017/DNA_trimmed/SRR4342129_1.paired.trimmed.fastq.gz /home/andreak/Genome_Analysis/Genome-Analysis/raw_data/3_Thrash_2017/DNA_trimmed/SRR4342129_2.paired.trimmed.fastq.gz 2> /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D1-SRR4342129_bwa/bwa_DNA_D1-SRR4342129.sam | samtools sort -o /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D1-SRR4342129_bwa/bwa_DNA_D1-SRR4342129.bam

# For D3
bwa index /home/andreak/Genome_Analysis/Genome-Analysis/data/Megahit/D3-SRR4342133_contigs/final.contigs.fa
bwa mem -t 10 /home/andreak/Genome_Analysis/Genome-Analysis/data/Megahit/D3-SRR4342133_contigs/final.contigs.fa /home/andreak/Genome_Analysis/Genome-Analysis/raw_data/3_Thrash_2017/DNA_trimmed/SRR4342133_1.paired.trimmed.fastq.gz /home/andreak/Genome_Analysis/Genome-Analysis/raw_data/3_Thrash_2017/DNA_trimmed/SRR4342133_2.paired.trimmed.fastq.gz 2> /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D3-SRR4342133_bwa/bwa_DNA_D3-SRR4342133.sam | samtools sort -o /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D3-SRR4342133_bwa/bwa_DNA_D3-SRR4342133.bam

# Create depth file 
jgi_summarize_bam_contig_depths --outputDepth /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D1-SRR4342129_bwa/D1_depth.txt --pairedContigs /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D1-SRR4342129_bwa/D1_paired.txt /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D1-SRR4342129_bwa/*.bam
jgi_summarize_bam_contig_depths --outputDepth /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D3-SRR4342133_bwa/D3_depth.txt --pairedContigs /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D3-SRR4342133_bwa/D3_paired.txt /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D3-SRR4342133_bwa/*.bam

