#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 01:00:00
#SBATCH -J fastqc
#SBATCH --mail-type=ALL 
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se 

#script for quality check of trimmed DNA and untrimmed and trimmed RNA.

#load the necessary modules
module load bioinfo-tools 
module load FastQC


#Check quality in trimmed DNA
#for file in /home/andreak/Genome_Analysis/3_Thrash_2017/DNA_trimmed/* 
#do 
#fastqc $file -o /home/andreak/Genome_Analysis/Genome-Analysis/data/FastQC/DNA_fastqc
#done

#Check quality for untrimmed RNA
for file in /home/andreak/Genome_Analysis/3_Thrash_2017/RNA_untrimmed/* 
do 
fastqc $file -o /home/andreak/Genome_Analysis/Genome-Analysis/data/FastQC/RNA_untrim_fastqc
done

#Check quality for trimmed RNA
#for file in /home/andreak/Genome_Analysis/Genome-Analysis/data/Trimmomatic/*
#do 
#fastqc $file -o /home/andreak/Genome_Analysis/Genome-Analysis/data/FastQC/RNA_trim_fastqc
#done
