#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 01:00:00
#SBATCH -J trim_RNA
#SBATCH --mail-type=ALL 
#SBATCH --mail-user stavroula.andreakou.9085@student.uu.se 

#script for quality check of trimmed DNA and untrimmed and trimmed RNA.

#load the necessary modules
module load bioinfo-tools 
module load FastQC

SEQDIR="/home/andreak/Genome_Analysis/3_Thrash_2017"
OUTDIR="/home/andreak/Genome_Analysis/Genome-Analysis/data/FastQC"

#input for trimmed RNA 
SQD="/home/andreak/Genome_Analysis/Genome-Analysis/data/Trimmomatic"

#Check quality in trimmed DNA
for file in SEQDIR/DNA_trimmed/* 
do 
fastqc $file -o OUTDIR 
done

#Check quality for untrimmed RNA
#for file in SEQDIR/* 
#do 
#fastqc $file -o OUTDIR/RNA_fastqc_raw
#done

#Check quality for trimmed RNA
#for file in SQD/*
#do 
#fastqc $file -o OUTDIR/RNA_fastqc_trimmed
#done
