#!/bin/bash -l
SBATCH -A uppmax2022-2-5 -M snowy
SBATCH -p core 
SBATCH -n 2 
SBATCH -J qualitycheck 
SBATCH -t 1:00:00 --qos=short 
SBATCH --mail-type=ALL 
SBATCH --mail-user stavroula.andreakou.9085@student.uu.se 

#script for quality check of trimmed DNA and untrimmed and trimmed RNA: we need FastQC tool load the necessary modules

module load bioinfo-tools FastQC

#Check quality in trimmed DNA
for file in /home/andreak/Genome_Analysis/3_Thrash_2017/DNA_trimmed/* do fastqc $file -o 
/home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/preprocessing/DNA_fastqc done

#Check quality for untrimmed RNA
for file in /home/andreak/Genome_Analysis/3_Thrash_2017/RNA_trimmed/* do fastqc $file -o 
/home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/preprocessing/RNA_fastqc_raw
done

#Check quality for trimmed RNA
for file in /home/andreak/GenomeAnalysis/GenomeAnalysis/data/raw_data/RNA_trimme$
/home/pcr98/GenomeAnalysis/GenomeAnalysis/analysis/preprocessing/RNA_fastqc_raw
done
